export const ADD_CAT = 'add:cat'
export const USER_LOGGED_IN = 'USER_LOGGED_IN'
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'
export const USER_UPDATED = 'USER_UPDATED'
export const WEB3_INITIALIZED = 'WEB3_INITIALIZED'
